name: quick_js
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter



  flutter_qjs:
    git:
      url: https://github.com/jadehh/flutter_qjs.git
      ref: d70fd9eacd6e80c733db81a91c082d62c7f6567d

  flutter_log:
    git:
      url: https://github.com/jadehh/flutter_log.git
      ref: f4f911401d13cee9edbeab1edcf8622c63fd3b93

  uuid: ^4.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/js/
    - assets/js/lib/


