name: ok_http
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.0



dependencies:
  dio: ^5.7.0 #网络请求
  flutter_cache_manager: ^3.4.1
  flutter_log:
    git:
      url: https://github.com/jadehh/flutter_log.git
      ref: f4f911401d13cee9edbeab1edcf8622c63fd3b93


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
